# -*- coding: utf-8 -*-
"""Numpy

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HWMOx3bA04nCynEmIs-KcpR7oIGqGZcx
"""

# Commented out IPython magic to ensure Python compatibility.
l = range(1000)
# %timeit [i**2 for i in l]

import numpy as np
a = np.array([1,2,3,4,5])
a
a.ndim
a.shape
len(a)

c = np.array([[[1,2],[2,3]],[[2,3],[3,4]]])
c
c.ndim
c.shape
len(c)

b = np.array([[1,2,3],[1,2,3]])
b.ndim
b.shape
len(b)

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
a = np.arange(1000)
# %timeit a**2
a.shape

d =np.arange(1,10,2)
d

a = np.linspace(0,1,6)
a

a  = np.ones((3,3))
a

np.eye(3)

np.eye(3,2)

h = np.diag((1,2,3,4))
np.diag(h)
print(h[1,1])
h[1,2] = 7
h



x = np.random.rand(5)
x

a =np.arange(10)
a.dtype

a = np.arange(10,dtype = "float64")
a
print(a[5])

# a = np.arange(10)
a[1:8:2]
a[1:] = 10
a

b = np.arange(5)
a[5:]= b [::-1]
a

a = np.arange(10)
a

b = a[::2]
b

np.shares_memory(a,b)  #creating a view to be space effecient

b[0]= 10
b
a

a =np.arange(10)
c = a[::2].copy() #force a copy
np.shares_memory(a,c)

a = np.random.randint(0,20,15)
a

mask = (a% 2 ==0)
c = a[mask]
c

a[mask] = -1
a

a =np.arange(0,100,10)
a[[2,3,2,4,2]]

a[[2,3]] = 100
a