# -*- coding: utf-8 -*-
"""Numpy3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZTe9DIthmQz19j7D0pbP1wlnrKxJ5MGe
"""

from google.colab import files
uploaded = files.upload()

import numpy as np
data = np.loadtxt('data.txt')
data

year, hares, lynxes, ggg, gggj = data.T
print(year)

populations = data[:,1:]
populations

populations.std(axis=0)

np.argmax(populations, axis = 1)  #highest value in row (index)

a = np.tile(np.arange(0,40,10), (3,1))
print(a)

a = a.T
print(a)

a = np.arange(0,40,10)
a = a[:,np.newaxis]
a.shape     #broadcasting third type confusion

#flattening
a = np.array([[1,2,3],[4,5,6]])
a.ravel()
#reshape() reshapes a flattened array into the no. of rows and coulmns passed

a = np.arange(4)
a.resize((8,))
a

a = np.array([[5,4,6],[2,3,2]])
b = np.sort(a, axis=1)
b
a.sort(axis=1)
a
#argsort (gives position of sorted data)